[package]
name = "cjconv"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
csv = "1.2"
serde_json = { version = "1.0", features = ["preserve_order"] }
indexmap = "2.0"